AY2223S2-CS2113-T13-1/tp

src/main/java/seedu/duke/Currency.java, src/main/java/seedu/duke/constants/Message.java, src/main/java/seedu/duke/ui/Ui.java
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
I have added in the `Ui` class.
Fixes # (issue)
#22
=> 22-UI-class

src/main/java/seedu/duke/AccountList.java, src/main/java/seedu/duke/commands/BalanceCommand.java, src/main/java/seedu/duke/commands/CommandType.java, src/main/java/seedu/duke/commands/DeleteAccountCommand.java, src/main/java/seedu/duke/constants/ErrorMessage.java, src/main/java/seedu/duke/constants/Message.java, src/main/java/seedu/duke/exceptions/AccountNotEmptyException.java, src/main/java/seedu/duke/exceptions/InvalidDeleteAccountCommandException.java, src/main/java/seedu/duke/parser/Parser.java, src/test/java/seedu/duke/commands/DeleteAccountCommandTest.java
=> 14 delete account command

src/main/java/seedu/duke/AccountList.java, src/main/java/seedu/duke/commands/AddCommand.java, src/main/java/seedu/duke/commands/BalanceCommand.java, src/main/java/seedu/duke/commands/WithdrawCommand.java, src/test/java/seedu/duke/commands/BalanceCommandTest.java, src/test/java/seedu/duke/commands/WithdrawCommandTest.java
schema)
```docs
Fixes bug with the display message for AddCommand, and also fixes a logic issue where the precision of adds were lost.
```
Fixes #48 
```docs
```
=> 48 printed message for add account should not be divided by 100

src/main/java/seedu/duke/commands/CommandType.java, src/main/java/seedu/duke/commands/HelpCommand.java, src/main/java/seedu/duke/constants/Message.java, src/main/java/seedu/duke/parser/Parser.java
schema)
```docs
```
Fixes #51 
```docs
```
=> 51 help command

src/main/java/seedu/duke/commands/WithdrawCommand.java
schema)
```docs
```
Fixes #53
```docs
```
=> 53 wrong withdraw message

DefaultCodeStyle.xml, src/main/java/seedu/duke/AccountList.java, src/main/java/seedu/duke/commands/WithdrawCommand.java, src/main/java/seedu/duke/constants/Message.java
schema)
```docs
```
Fixes #56
```docs
```
=> 55 bug fix delete command

src/main/java/seedu/duke/commands/CreateAccountCommand.java, src/main/java/seedu/duke/constants/ErrorMessage.java, src/test/java/seedu/duke/commands/CreateAccountTest.java
Improve the misleading error messages associated with the create-account command
Fix misleading error message for create-account command to send clearer information to the user when create-account fails
Fixes #46 
Take note of the INVALID_CREATE_ACCOUNT_COMMAND error message in ErrorMessage.java as that is the only significant change
=> Arif khalid update create account error messages

src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/commands/BalanceCommand.java, src/main/java/seedu/duke/commands/Command.java, src/main/java/seedu/duke/commands/CommandType.java, src/main/java/seedu/duke/commands/ExitCommand.java, src/main/java/seedu/duke/commands/HelpCommand.java, src/test/java/seedu/duke/commands/AddCommandTest.java, src/test/java/seedu/duke/commands/BalanceCommandTest.java, src/test/java/seedu/duke/commands/DeleteAccountCommandTest.java
schema)
```docs
```
Fixes #
```docs
```
=> Handle undefine command

src/main/java/seedu/duke/Transaction.java, src/main/java/seedu/duke/TransactionManager.java
schema)
```docs
Added more attributes to the transaction class
```
Fixes #
```docs
```
=> Arif khalid update transaction class

.gitignore, src/main/java/seedu/duke/Account.java, src/main/java/seedu/duke/AccountList.java, src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/TransactionManager.java, src/main/java/seedu/duke/api/ExchangeRates.java, src/main/java/seedu/duke/commands/AddCommand.java, src/main/java/seedu/duke/commands/ExchangeCommand.java, src/main/java/seedu/duke/commands/WithdrawCommand.java, src/main/java/seedu/duke/storage/LocalDateTimeAdapter.java, src/main/java/seedu/duke/storage/Store.java, src/main/java/seedu/duke/storage/StoreInterface.java, src/main/java/seedu/duke/storage/TestStore.java, src/test/java/seedu/duke/commands/AddCommandTest.java, src/test/java/seedu/duke/commands/BalanceCommandTest.java, src/test/java/seedu/duke/commands/CreateAccountTest.java, src/test/java/seedu/duke/commands/DeleteAccountCommandTest.java, src/test/java/seedu/duke/commands/ShowRateCommandTest.java, src/test/java/seedu/duke/commands/TransactionCommandTest.java, src/test/java/seedu/duke/commands/WithdrawCommandTest.java
An interface is used to define the functions for the Store so that a dummy store can be used in unit tests.
schema)
```docs
```
Fixes #
```docs
```
=> Add the ability to write to file.

src/main/java/seedu/duke/AccountList.java, src/main/java/seedu/duke/commands/CreateAccountCommand.java, src/main/java/seedu/duke/commands/DeleteAccountCommand.java, src/main/java/seedu/duke/storage/LocalDateTimeAdapter.java, src/main/java/seedu/duke/storage/Store.java
schema)
```docs
```
Fixes #
```docs
```
=> Fix issue with balances being saved and loaded wrongly

docs/DeveloperGuide.md
schema)
```docs
```
Fixes #
```docs
```
=> Fix typo in DeveloperGuide

src/main/java/seedu/duke/Duke.java
There is an indeterminate reason why the exit command does not end the program as the end of the main method is reached. As such, I have written a workaround that simply calls system.exit() right before the end of the main method to end the program.
schema)
```docs
Fixes the issue with the exit command where it does not immediately close the program
```
Fixes #146 
```docs
```
=> Fix the exit command not immediately terminating the program

src/main/java/seedu/duke/commands/WithdrawCommand.java, src/main/java/seedu/duke/constants/ErrorMessage.java, src/main/java/seedu/duke/exceptions/InvalidWithdrawAmountException.java
schema)
```docs
```
Fixes #169 
Fixes #165 
Fixes #158 
Fixes #125 
I decided not to use dynamic error message because I thought that we did not do that throughout the whole project so it will be a bit odd if I only do so in my withdrwCommand.
```docs
```
=> Wrong withdraw comannd exception desc

src/main/java/seedu/duke/ui/Ui.java
In order to tackle this change, I have added in a replaceAll method that is used to replaced all sets of multiple spaces with a single spacing. This ensures that the input that we received from the user is what we expect it to be and can be processed accordingly.
Fixes #170
=> 170-pe-dtester-a-cannot-tackle-extra-spaces

src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/TransactionManager.java, src/main/java/seedu/duke/commands/AddCommand.java, src/main/java/seedu/duke/commands/Command.java, src/main/java/seedu/duke/commands/ExchangeCommand.java, src/main/java/seedu/duke/commands/WithdrawCommand.java, src/main/java/seedu/duke/constants/DateConstants.java, src/main/java/seedu/duke/constants/ErrorMessage.java, src/main/java/seedu/duke/exceptions/AmountTooPreciseException.java
schema)
```docs
Fixes the issue of too precise amounts being passed in by the user
Fixes the issue of some dates being invalid but treated as valid
```
Fixes #131 
Fixes #174 
```docs
```
=> Arif khalid fix pe dry run issues

src/main/java/seedu/duke/commands/ExchangeCommand.java, src/main/java/seedu/duke/constants/ErrorMessage.java
schema)
```docs
Specifies which account is missing when error is caught using exchange command
```
Fixes # 163
```docs
```
=> Exchange cmd ped

src/main/java/seedu/duke/commands/AddCommand.java, src/main/java/seedu/duke/commands/WithdrawCommand.java, src/main/java/seedu/duke/constants/ErrorMessage.java, src/main/java/seedu/duke/exceptions/DescriptionTooLongException.java
schema)
```docs
```
Fixes #179 
```docs
```
=> Limit description 100char

docs/UserGuide.md
schema)
```docs
```
Fixes #126
Fixs #196 
```docs
```
=> Add section on currency and date related inputs to the UG

src/main/java/seedu/duke/exceptions/AccountNotEmptyException.java, src/main/java/seedu/duke/exceptions/InvalidShowrateArgumentException.java, src/main/java/seedu/duke/exceptions/InvalidWithdrawCommandException.java, src/main/java/seedu/duke/exceptions/NotEnoughInAccountException.java
schema)
```docs
```
Fixes #
```docs
```
=> Remove files in wrong directory

src/main/java/com/moneymoover/commands/BalanceCommand.java, src/main/java/com/moneymoover/constants/ErrorMessage.java, src/main/java/com/moneymoover/constants/Message.java
I have made the messages for the BalanceCommand clearer by telling the user that there is no accounts to be displayed, or if the balance command does not follow a certain format.
schema)
Fixes #206 #211
=> Add in the message for balances

docs/DeveloperGuide.md, docs/UserGuide.md, docs/team/bawfen.md, src/main/java/com/moneymoover/Account.java, src/main/java/com/moneymoover/AccountList.java, src/main/java/com/moneymoover/api/ExchangeRates.java, src/main/java/com/moneymoover/storage/Store.java
schema)
```docs
```
Fixes #
```docs
```
=> Manual testing instructions

docs/UserGuide.md
Standardise the documentation in the User Guide
schema)
```docs
Standardise documentation of UG such that it looks as if it were written by a single developer
```
Fixes #218 #219 #220 
```docs
```
=> Arif khalid standardise documentation in UG

docs/UserGuide.md, docs/team/woowenjun99.md
schema)
```docs
```
Fixes #
```docs
```
=> Update wen ppp
